services:
  melon:
    image: melon
    user: "1000:1000"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - MelonData:/Data
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "${CALLBACK_PORT:-2742}:${CALLBACK_PORT:-2742}"
volumes:
  MelonData: