services:
  melon:
    image: melon
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - MelonData:/app/Data
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "${CALLBACK_PORT:-2742}:${CALLBACK_PORT:-2742}"
volumes:
  MelonData: